-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
package.path = package.path .. ";/home/mahesh/.config/hypr/modules/?.lua"
require("modules.monitors")
require("modules.programs")
require("modules.autostart")
require("modules.env")
require("modules.decorations")
require("modules.animations")
require("modules.windowrules")
require("modules.layout")
require("modules.misc")
require("modules.input")
require("modules.binds")
