-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- theme-changer: begin

hl.config({
    general = {
        no_fade_in = false,
        grace = 0,
        disable_loading = true,
    },
})

hl.config({
    background = {
        path = "screenshot",
        blur_passes = 3,
        blur_size = 8,
    },
})
-- NOTE: Section 'background' may be a plugin or custom section; verify the output

hl.config({
    shape = {
        size = { "100%", "100%" },
        color = { "rgba(17", 20, 14, "0.6)" },
        rounding = 0,
        border_size = 0,
        position = { 0, 0 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'shape' may be a plugin or custom section; verify the output

hl.config({
    input-field = {
        size = { 200, 40 },
        outline_thickness = 2,
        dots_size = 0.3,
        dots_spacing = 0.2,
        dots_center = true,
        outer_color = { "rgb(171", 210, "144)" },
        inner_color = { "rgb(17", 20, "14)" },
        font_color = { "rgb(225", 228, "217)" },
        fade_on_empty = true,
        placeholder_text = "Password",
        hide_input = false,
        position = { 0, 0 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'input-field' may be a plugin or custom section; verify the output

hl.config({
    label = {
        text = TIME12,
        color = { "rgb(225", 228, "217)" },
        font_size = 128,
        font_family = "SF Pro Display Bold",
        position = { 0, 200 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

hl.config({
    label = {
        text = { "Hi", "Mahesh" },
        color = { "rgb(171", 210, "144)" },
        font_size = 32,
        font_family = "SF Pro Display Bold",
        position = { 0, 80 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- theme-changer: end
