-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
package.path = package.path .. ";/home/mahesh/.config/hypr/modules/?.lua"
-- Source: ~/.config/hypr/modules/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.monitors")
-- Source: ~/.config/hypr/modules/programs.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.programs")
-- Source: ~/.config/hypr/modules/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.autostart")
-- Source: ~/.config/hypr/modules/env.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.env")
-- Source: ~/.config/hypr/modules/decorations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.decorations")
-- Source: ~/.config/hypr/modules/animations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.animations")
-- Source: ~/.config/hypr/modules/windowrules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.windowrules")
-- Source: ~/.config/hypr/modules/layout.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.layout")
-- Source: ~/.config/hypr/modules/misc.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.misc")
-- Source: ~/.config/hypr/modules/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.input")
-- Source: ~/.config/hypr/modules/binds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.binds")
