# Generado por theme-changer — no editar directamente

general {
    col.active_border   = rgba(adc6ffff) rgba(bfc6dcff) 45deg
    col.inactive_border = rgba(44474faa)
}

decoration {
    shadow {
        color = rgba(000000aa)
    }
}

# Blur de capas
blurls = wlogout
blurls = rofi
