# Generado por theme-changer — no editar directamente

general {
    col.active_border   = rgba(4C8CE4ff) rgba(91D06Cff) 45deg
    col.inactive_border = rgba(25324Aaa)
}

decoration {
    shadow {
        color = rgba(000000aa)
    }
}

# Blur de capas
blurls = wlogout
blurls = rofi
