# Generado por theme-changer — no editar directamente

general {
    col.active_border   = rgba(de1b1bff) rgba(ff6a00ff) 45deg
    col.inactive_border = rgba(1e2024aa)
}

decoration {
    shadow {
        color = rgba(0f1014aa)
    }
}

# Blur de capas
blurls = wlogout
blurls = rofi
