##############################
### WINDOWS AND WORKSPACES ###
##############################

workspace = 1, persistent:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true
workspace = 5, persistent:true

# Suppress windows maximising
windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# Float - Gnome Calculator
windowrule {
    name = gnome-calculator-float
    match:class = ^(org.gnome.Calculator)$
    float = yes
}

# Inhibiting idle in Zen for fullscreen youtube videos
windowrule {
    name = zen-fullscreen-inhibit-idle
    match:class = ^(zen)$
    idle_inhibit = fullscreen
}

# Layer rules for Waybar
# layerrule = blur on, match:namespace waybar
# layerrule = ignore_alpha 0.1, match:namespace waybar
# layerrule = animation popin 75%, match:namespace waybar

# Layer rules for Rofi
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.4, match:namespace rofi
layerrule = animation popin 75%, match:namespace rofi
layerrule = dim_around true, match:namespace rofi

# Layer rules for Swaync Control Center
layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.4, match:namespace swaync-control-center
layerrule = animation slide right, match:namespace swaync-control-center
layerrule = dim_around true, match:namespace swaync-control-center

# Layer rules for Swaync notif window 
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.4, match:namespace swaync-notification-window
layerrule = animation slide right, match:namespace swaync-notification-window
