# Generado por theme-changer — no editar directamente
# Para personalizar colores: editar ~/.config/kitty/kitty.conf

foreground            #c0caf5
background            #1a1b26
selection_foreground  #1a1b26
selection_background  #7aa2f7
cursor                #7aa2f7
cursor_text_color     #1a1b26
url_color             #7aa2f7

# Terminal colors (0-7 normal, 8-15 bright)
color0   #1f2335
color1   #f7768e
color2   #9ece6a
color3   #e0af68
color4   #7aa2f7
color5   #bb9af7
color6   #73daca
color7   #a9b1d6
color8   #292e42
color9   #f7768e
color10  #9ece6a
color11  #e0af68
color12  #7aa2f7
color13  #ff75a0
color14  #73daca
color15  #c0caf5

# Bordes
active_border_color   #7aa2f7
inactive_border_color #3b4261
bell_border_color     #f7768e
