# Generado por theme-changer — no editar directamente
# Para personalizar colores: editar ~/.config/kitty/kitty.conf

foreground            #d3dae3
background            #1c2b23
selection_foreground  #1c2b23
selection_background  #41ae76
cursor                #41ae76
cursor_text_color     #1c2b23
url_color             #41ae76

# Terminal colors (0-7 normal, 8-15 bright)
color0   #22352b
color1   #da4453
color2   #27ae60
color3   #fdbc4b
color4   #3daee9
color5   #666a73
color6   #41ae76
color7   #666a73
color8   #203027
color9   #da4453
color10  #27ae60
color11  #fdbc4b
color12  #41ae76
color13  #da4453
color14  #41ae76
color15  #d3dae3

# Bordes
active_border_color   #41ae76
inactive_border_color #1c2b23
bell_border_color     #da4453
