# Generado por theme-changer — no editar directamente
# Para personalizar colores: editar ~/.config/kitty/kitty.conf

foreground            #e2e2e9
background            #111318
selection_foreground  #111318
selection_background  #adc6ff
cursor                #adc6ff
cursor_text_color     #111318
url_color             #adc6ff

# Terminal colors (0-7 normal, 8-15 bright)
color0   #44474f
color1   #ffb4ab
color2   #debcdf
color3   #3f4759
color4   #adc6ff
color5   #debcdf
color6   #2b4678
color7   #c4c6d0
color8   #282a2f
color9   #ffb4ab
color10  #debcdf
color11  #3f4759
color12  #adc6ff
color13  #93000a
color14  #2b4678
color15  #e2e2e9

# Bordes
active_border_color   #adc6ff
inactive_border_color #44474f
bell_border_color     #ffb4ab
