--################
--## AUTOSTART ###
--################

-- exec-once = ~/.config/waybar/scripts/launch.sh
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- For GTK (Gnome/System apps like Dolphin and Browsers)

-- Start the Gnome Keyring daemon

-- For generating the file list cache on login for rofi

-- For using kde passwords gui for authenticating

-- Start custom volume osd using swaync

-- For clipboard stuff

-- For hyprland stuff

-- JamesDSP for audio equalizer

-- KDE Connect notification sync with phone

hl.on("hyprland.start", function()
	hl.exec_cmd("uwsm app -- waybar")
	hl.exec_cmd("uwsm app -- hypridle")
	hl.exec_cmd("uwsm app -- awww-daemon")
	hl.exec_cmd("uwsm app -- swaync")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
	hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
	hl.exec_cmd("~/.local/bin/rofi-update-cache.sh")
	hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
	hl.exec_cmd("swayosd-server")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("wl-clip-persist --clipboard regular")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("jamesdsp")
	hl.exec_cmd("kdeconnect-indicator")
end)
