--####################
--## LOOK AND FEEL ###
--####################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
	general = {
		gaps_in = 6,
		gaps_out = 12,
		border_size = 1,
		col = {
			active_border = "rgba(d8d8d8ff)",
			inactive_border = "rgba(444444ff)",
		},
		allow_tearing = true,
		layout = "dwindle",
	},
	decoration = {
		rounding = 12,
		rounding_power = 4,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 8,
			render_power = 2,
			color = "rgba(080808aa)",
		},
		blur = {
			enabled = true,
			size = 12,
			passes = 2,
			new_optimizations = true,
			ignore_opacity = true,
			noise = 0.05,
			contrast = 1.0,
			brightness = 0.75,
			popups = false,
			popups_ignorealpha = 0.01,
		},
	},
})
