--############
--## INPUT ###
--############

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

hl.device({
	name = "epic-mouse-v1",
	sensitivity = 0,
})

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",
		follow_mouse = 1,
		accel_profile = "flat",
		sensitivity = -0.3,
		touchpad = {
			natural_scroll = true,
		},
	},
})
