--##############
--## LAYOUTS ###
--##############

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
	dwindle = {
		-- pseudotile = true
		preserve_split = true,
		force_split = 2,
	},
	master = {
		new_status = "slave",
	},
})
