--###############
--## MONITORS ###
--###############

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
	output = "HDMI-A-1",
	mode = "1920x1080@100",
	position = "0x0",
	scale = "1",
})

-- Comment and uncomment the disabled line accordingly

hl.monitor({
	output = "eDP-1",
	mode = "1600x900@60",
	position = "auto",
	scale = "1",
	disabled = true,
})
