###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$browser = helium-browser
$menu = rofi -show combi -combi-modi "drun,files:~/.local/bin/rofi-file-search.sh" -modi combi -show-icons -icon-theme "$HOME/.local/share/icons/YAMIS" -drun-display-format "{name}" -threads 0 -mem-cache-size 32 -scroll-method 1
$calculator = rofi -show calc -modi calc -no-show-match -no-history -theme-str 'window {width:300px;} mainbox {children:[inputbar,message];}'
