--##################
--## MY PROGRAMS ###
--##################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

terminal = "kitty"
fileManager = "nautilus"
browser = "helium-browser"
appMenu = 'pkill rofi || rofi -show combi -combi-modi "drun" -modi combi -threads 2 -mem-cache-size 32'
fileSearch =
	"pkill rofi || rofi -show combi -combi-modi 'files:~/.local/bin/rofi-file-search.sh' -modi combi -threads 2 -mem-cache-size 32"
calculator =
	"pkill rofi || rofi -show calc -modi calc -no-show-match -no-history -theme-str 'window {width:500px;} mainbox {children:[inputbar,message];}'"
execScripts =
	"find ~/.local/bin -maxdepth 1 -type f -executable -printf '%f\n' | rofi -dmenu -no-show-icons -theme-str 'window { width: 26ch; } mainbox { children: [ 'listview' ]; }' | xargs -r -I % bash -c '~/.local/bin/'%''"
powerMenu = "~/.local/bin/rofi-power-menu.sh"
