###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = nautilus
$browser = helium-browser
$menu = rofi -show combi -combi-modi "drun" -modi combi -threads 1
$filesearch = rofi -show combi -combi-modi "files:~/.local/bin/rofi-file-search.sh" -modi combi -threads 2 -mem-cache-size 32
$calculator = rofi -show calc -modi calc -no-show-match -no-history -theme-str 'window {width:500px;} mainbox {children:[inputbar,message];}'
