--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.workspace_rule({ workspace = "1", persistent = true, monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "2", persistent = true, monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "3", persistent = true, monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "4", persistent = true, monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "5", persistent = true, monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "6", persistent = true, monitor = "eDP-1" })
hl.workspace_rule({ workspace = "7", persistent = true, monitor = "eDP-1" })
hl.workspace_rule({ workspace = "8", persistent = true, monitor = "eDP-1" })
hl.workspace_rule({ workspace = "9", persistent = true, monitor = "eDP-1" })
hl.workspace_rule({ workspace = "10", persistent = true, monitor = "eDP-1" })

-- Suppress windows maximising
hl.window_rule({
	name = "suppress-maximize-events",
	match = {
		class = ".*",
	},
	suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},
	no_focus = true,
	opaque = true,
	no_blur = true,
})

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },
	move = "20 monitor_h-120",
	float = true,
})

-- Float - Gnome Calculator
hl.window_rule({
	name = "gnome-calculator-float",
	match = { class = "^(org.gnome.Calculator)$" },
	float = true,
	center = true,
})

-- Float - Btop
hl.window_rule({
	name = "btop-float",
	match = { class = "^(btop_floating)$" },
	float = true,
	center = true,
})

-- Inhibiting idle in Zen for fullscreen youtube videos
-- hl.window_rule({
-- 	name = "zen-fullscreen-inhibit-idle",
-- 	match = { class = "^(zen)$" },
-- 	idle_inhibit = "fullscreen",
-- })

-- Layer rules for Rofi
hl.layer_rule({
	match = { namespace = "rofi" },
	blur = true,
	ignore_alpha = 0.4,
	animation = "popin 90%",
	dim_around = true,
})

-- Layer rules for Swaync Control Center
hl.layer_rule({
	match = { namespace = "swaync-control-center" },
	blur = true,
	ignore_alpha = 0.4,
	animation = "slide right",
	dim_around = true,
})

-- Layer rules for Swaync notif window
hl.layer_rule({
	match = { namespace = "swaync-notification-window" },
	blur = true,
	ignore_alpha = 0.4,
	animation = "slide right",
})

hl.layer_rule({
	match = { namespace = "swayosd" },
	blur = true,
	ignore_alpha = 0.4,
	animation = "fade",
})

-- Fix transparent/blurred Java popup for SKLauncher
hl.window_rule({
	match = { class = "^(SKLauncher)$" },
	opaque = true,
	no_blur = true,
})

-- Fallback check for alternative sklauncher string patterns
hl.window_rule({
	match = { class = "^(sklauncher|-)$" },
	opaque = true,
	no_blur = true,
})

-- Fix transparent/blurred Tauri popup for Asyar
hl.window_rule({
	match = { class = "^(asyar)$" },
	opaque = true,
	no_blur = true,
})
