--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.workspace_rule({
	workspace = "1",
	persistent = true,
})

hl.workspace_rule({
	workspace = "2",
	persistent = true,
})

hl.workspace_rule({
	workspace = "3",
	persistent = true,
})

hl.workspace_rule({
	workspace = "4",
	persistent = true,
})

hl.workspace_rule({
	workspace = "5",
	persistent = true,
})

-- Suppress windows maximising
hl.window_rule({
	name = "suppress-maximize-events",
	match = {
		class = ".*",
	},
	suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},
	no_focus = true,
})

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",
	match = {
		class = "hyprland-run",
	},
	move = "20 monitor_h-120",
	float = true,
})

-- Float - Gnome Calculator
hl.window_rule({
	name = "gnome-calculator-float",
	match = {
		class = "^(org.gnome.Calculator)$",
	},
	float = true,
})

-- Inhibiting idle in Zen for fullscreen youtube videos
hl.window_rule({
	name = "zen-fullscreen-inhibit-idle",
	match = {
		class = "^(zen)$",
	},
	idle_inhibit = "fullscreen",
})

-- Layer rules for Waybar
-- layerrule = blur on, match:namespace waybar
-- layerrule = ignore_alpha 0.1, match:namespace waybar
-- layerrule = animation popin 75%, match:namespace waybar

-- Layer rules for Rofi
hl.layer_rule({
	match = { namespace = "match:namespace rofi" },
	-- TODO: manual review — unmapped layer rule: "blur on"
	ignore_alpha = 0.4,
	animation = "popin 75%",
	-- TODO: manual review — unmapped layer rule: "dim_around true"
})

-- Layer rules for Swaync Control Center
hl.layer_rule({
	match = { namespace = "match:namespace swaync-control-center" },
	-- TODO: manual review — unmapped layer rule: "blur on"
	ignore_alpha = 0.4,
	animation = "slide right",
	-- TODO: manual review — unmapped layer rule: "dim_around true"
})

-- Layer rules for Swaync notif window
hl.layer_rule({
	match = { namespace = "match:namespace swaync-notification-window" },
	-- TODO: manual review — unmapped layer rule: "blur on"
	ignore_alpha = 0.4,
	animation = "slide right",
})
